language: node_js
sudo: false
node_js:
  - '6.9'
after_success:
  - npm run build
before_deploy:
  - cd dist
deploy:
  provider: npm
  email: jeremy@bytelabs.co
  skip_cleanup: true
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
